### ISSUE TITLE
fresh install 

### ISSUE THREAD

**Issue by luscaGIT** [plamish/xcomfort#15]
Hi,

Im trying to install your Xcomfort intregration to use with my newly installed ZIP Screens.
Would like to get the lux value from a HUE outdoor sensor and make the zip screens go down on a value and up on another.

But the issue for me is that I cant login it seems. I provided a screenshot of the error log. But im not able to pinpoint the issue with my lack of code experience.
Ive tried different usernames but does not seems to make a difference. 

Installed via HACS

![image](https://user-images.githubusercontent.com/97387590/148688179-a32c2b50-c85d-4c56-a8a6-87c587a42a2f.png)

**Comment by plamish** [comment]
Hey luscaGIT, message error says Home Assistant can't connect with your SHC xComfort box. I advise to login to SHC and validate 192.168.83 is correct IP address and Local HTTP Connection is enabled. You can do both in SHC's System->Network tab. 
If both are OK check if SHC is reachable from Home Assistant. Simplest way is to install Terminal Add-on and run `wget 192.168.1.83`. If all is fine you will get 401 error with authentication failed message.

**Comment by luscaGIT** [comment]
Ok, thanks for the quick reply. 
It seems I do not have access to the remote web admin page.
Cant remember to ever seen or received a remote access key. 

according to my router the ip is idd. 192.168.1.83, confirmed with mac-address..
I assume the web admin page is the area you are talking about to enable the HTTP Connection, as I can not find it in either xSetup or MRF.. 

![image](https://user-images.githubusercontent.com/97387590/148699862-959a4856-7c9a-404c-be39-d0762533fa19.png)

**Comment by plamish** [comment]
Login to https://mysmarthome.eaton.com/ .Then in 2.System-> Network tab you can enable local connection.

**Comment by luscaGIT** [comment]
> Login to https://mysmarthome.eaton.com/ .Then in 2.System-> Network tab you can enable local connection.
> 
> If you can't see Configuration console you likely have user not admin login

Yes that is true.. 
Im trying to get a hold of this " remote access key" that I have to have.
I cant recall having a key of that sort on the install of the X-1 controller 6years ago.

Ive sent an email to Eaton to ask.

**Comment by luscaGIT** [comment]
Oh I see, there is a difference between "SHC" and "X-1" . 
I have the newer X-1, does that mean that this integration does not work for me?

**Comment by plamish** [comment]
Frankly, I haven't heard about X-1 before. It looks like a different solution from SHC: https://byggebolig.no/smarthus/xcomfort-shc-eller-sensio-x1
and seems doesn't support direct HTTP connection. Maybe it has other options to integrate with HA like IFTTT

**Comment by luscaGIT** [comment]
Hi, sorry to bother you again..
just to be clear

this is the device I have and trying to intregrate : 
![image](https://user-images.githubusercontent.com/97387590/149535661-11a2b37e-1605-4e71-91c9-cfa6ae17cfde.png)

here is the IP from xsetup
![image](https://user-images.githubusercontent.com/97387590/149535612-e45b6f92-c411-4e3a-97f3-db82864587ec.png)

and the error log : 
2022-01-14 10:59:41 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-14 10:59:41 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xcomfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-14 10:59:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry XComfort for xcomfort
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.83', 80)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/xcomfort/__init__.py", line 23, in async_setup_entry
await coordinator.xc.connect()
File "/config/custom_components/xcomfort/xcomfortAPI.py", line 42, in connect
async with self.session.get(self.url, auth=auth) as response:
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.83:80 ssl:default [Connect call failed ('192.168.1.83', 80)]
2022-01-14 11:00:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
result = await self._async_handle_step(flow, flow.init_step, data, init_done)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/usr/src/homeassistant/homeassistant/components/samsungtv/config_flow.py", line 271, in async_step_ssdp
self._manufacturer = discovery_info.upnp[ssdp.ATTR_UPNP_MANUFACTURER]
KeyError: 'manufacturer'

Is the device I have wrong from what you made the app for or do I need to open a port ?
The htttp/ipadress /system/config link from docu doesent give any info either(ofc used the device's ip).

**Comment by plamish** [comment]
The integration supports Eaton SHC device, which apparently looks very similar to yours, but according to what I learned from the Internet is a different device. Sensio doesn't provide local http server with json-rpc protocol what is how the integration communicates with Eaton SHC.

I'd advise to contact Sensio vendor with question what are the possible integration capabilities. I found on their website that Google Home integration is feasible, so there is a chance they have something else what is supported by Home Assistant

Good luck

**Comment by BirgerKo** [comment]
Hi, I can shed some light on this. Sensio is separate company working with home automations. Sensio has some sort of collaboration with Eaton and the X-1 is the same HW as the SHC. The SW is completely different.
![image](https://user-images.githubusercontent.com/35929926/159355983-7c517a81-572e-423c-9b51-4b9e374893f4.png)
