### ISSUE TITLE
Integrations stopped working after core update to 2018.8.7

### ISSUE THREAD

**Issue by gulli1986** [plamish/xcomfort#3]
See below, the integration just stopped working.
Any way to fix this?

```
2021-08-16 17:15:34 ERROR (MainThread) [custom_components.xcomfort] Error fetching xcomfort data: Error API
2021-08-16 17:15:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up xcomfort platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/sensor.py", line 15, in async_setup_entry
for device in coordinator.data:
TypeError: 'NoneType' object is not iterable
2021-08-16 17:15:34 ERROR (MainThread) [homeassistant.components.switch] Error while setting up xcomfort platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/switch.py", line 13, in async_setup_entry
for device in coordinator.data:
TypeError: 'NoneType' object is not iterable
2021-08-16 17:15:34 ERROR (MainThread) [homeassistant.components.cover] Error while setting up xcomfort platform for cover
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/cover.py", line 19, in async_setup_entry
for device in coordinator.data:
TypeError: 'NoneType' object is not iterable
2021-08-16 17:15:34 ERROR (MainThread) [homeassistant.components.light] Error while setting up xcomfort platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/light.py", line 13, in async_setup_entry
for device in coordinator.data:
TypeError: 'NoneType' object is not iterable
```

Thanks!

**Comment by plamish** [comment]
Hey,
There is a file xcomfort_session in /config folder. Delete it and restart HA. This will solve the issue.
Hard to find the time to update the code to remove this bug, but will do it.
Cheers

**Comment by gulli1986** [comment]
That did the trick, thanks a lot!
