### ISSUE TITLE
KeyError for cover, button, switch, sensor, light

### ISSUE THREAD

**Issue by IsakMV** [plamish/xcomfort#34]
Problem while setting up xcomfort. Seems like the device dictonary is empty. Also scene dict is empty.
~~~~~~^^^^^^^^
2023-07-25 20:53:53.012 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up xcomfort platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/sensor.py", line 17, in async_setup_entry
if device['type'].find("Temp") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'
2023-07-25 20:53:53.016 ERROR (MainThread) [homeassistant.components.light] Error while setting up xcomfort platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/light.py", line 14, in async_setup_entry
if device['type'].find("DimAct") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'
2023-07-25 20:53:53.019 ERROR (MainThread) [homeassistant.components.switch] Error while setting up xcomfort platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/switch.py", line 14, in async_setup_entry
if device['type'].find("Switch") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'
2023-07-25 20:53:53.024 ERROR (MainThread) [homeassistant.components.button] Error while setting up xcomfort platform for button
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/button.py", line 14, in async_setup_entry
async_add_entities([xcScene(coordinator, i, scene['id'], scene['name'])])
~~~~~^^^^^^
KeyError: 'id'
2023-07-25 20:53:53.028 ERROR (MainThread) [homeassistant.components.cover] Error while setting up xcomfort platform for cover
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/cover.py", line 22, in async_setup_entry
if device['type'].find("Shutt") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'

**Comment by IsakMV** [comment]
Forgot to enable all the devices for the new zone i created. It's under Advanced->functions in the eaton smart home controller settings
