### ISSUE TITLE
new installation - problems

### ISSUE THREAD

**Issue by panzenpeda** [plamish/xcomfort#39]
hi there,
setup a new home assistant and also did a new firmware update on SHC and not getting it to work on HA

log says:

> Home Assistant Core
Error while setting up xcomfort platform for cover
23:07:04 – (FEHLER) Abdeckung
Error while setting up xcomfort platform for button
23:07:04 – (FEHLER) Taste
Error while setting up xcomfort platform for switch
23:07:04 – (FEHLER) Schalter
Error while setting up xcomfort platform for light
23:07:04 – (FEHLER) Licht
Error while setting up xcomfort platform for sensor
23:07:04 – (FEHLER) Sensor
HVAC_MODE_AUTO was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please create a bug report at https://github.com/plamish/xcomfort/issues
23:07:04 – (WARNUNG) Klima - Die Nachricht ist zum ersten Mal am 23:07:04 aufgetreten und erscheint 12 mal
TEMP_CELSIUS was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/plamish/xcomfort/issues
23:07:04 – (WARNUNG) helpers/deprecation.py - Die Nachricht ist zum ersten Mal am 23:07:04 aufgetreten und erscheint 2 mal
SUPPORT_CLOSE was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please create a bug report at https://github.com/plamish/xcomfort/issues
23:07:04 – (WARNUNG) Abdeckung - Die Nachricht ist zum ersten Mal am 23:07:04 aufgetreten und erscheint 10 mal

thanks for help

**Comment by panzenpeda** [comment]
additional log info

> 2024-01-10 23:06:30.402 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-10 23:06:30.404 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xcomfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-01-10 23:07:04.153 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.186 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_CLOSE was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.199 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_OPEN was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.209 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_STOP was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.220 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_OPEN_TILT was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN_TILT instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.232 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_CLOSE_TILT was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE_TILT instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.242 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_CLOSE was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.254 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_OPEN was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.271 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_STOP was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.284 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_OPEN_TILT was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN_TILT instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.298 WARNING (MainThread) [homeassistant.components.cover] SUPPORT_CLOSE_TILT was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE_TILT instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.318 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.338 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_COOL was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.COOLING instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.350 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_HEAT was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.359 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_IDLE was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.367 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_OFF was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.OFF instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.376 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.387 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.395 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.402 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_AUTO was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.411 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_DRY was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.420 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_FAN_ONLY was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.428 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_PRESET_MODE was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.436 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from xcomfort, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/plamish/xcomfort/issues
2024-01-10 23:07:04.448 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up xcomfort platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/sensor.py", line 16, in async_setup_entry
if device['type'].find("Temp") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'
2024-01-10 23:07:04.453 ERROR (MainThread) [homeassistant.components.light] Error while setting up xcomfort platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/light.py", line 14, in async_setup_entry
if device['type'].find("DimAct") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'
2024-01-10 23:07:04.456 ERROR (MainThread) [homeassistant.components.switch] Error while setting up xcomfort platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/switch.py", line 14, in async_setup_entry
if device['type'].find("Switch") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'
2024-01-10 23:07:04.460 ERROR (MainThread) [homeassistant.components.button] Error while setting up xcomfort platform for button
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/button.py", line 14, in async_setup_entry
async_add_entities([xcScene(coordinator, i, scene['id'], scene['name'])])
~~~~~^^^^^^
KeyError: 'id'
2024-01-10 23:07:04.463 ERROR (MainThread) [homeassistant.components.cover] Error while setting up xcomfort platform for cover
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/xcomfort/cover.py", line 22, in async_setup_entry
if device['type'].find("Shutt") >= 0:
~~~~~~^^^^^^^^
KeyError: 'type'
